const fs = require('fs');

// ===== NEW SKILLS =====
const skillDefs = [
  ['ai-model-distillation','AI','Distill large models into smaller, faster ones while preserving accuracy. Knowledge distillation, pruning, quantization-aware training.'],
  ['ai-prompt-chain-builder','AI','Build complex prompt chains that decompose tasks into subtasks with conditional branching and error recovery.'],
  ['ai-synthetic-data-generator','AI','Generate realistic synthetic datasets for ML training. Tabular, text, image, time-series with privacy guarantees.'],
  ['ai-model-ab-testing','AI','Run A/B tests between ML models in production with traffic splitting and automated rollback.'],
  ['ai-feature-store-design','AI','Design feature stores for ML pipelines. Online/offline serving, versioning, point-in-time correctness.'],
  ['ai-mlflow-registry','AI','Manage ML model lifecycle with MLflow. Experiment tracking, model registry, deployment staging.'],
  ['ai-vector-search-optimization','AI','Optimize vector similarity search for RAG. HNSW tuning, product quantization, hybrid search.'],
  ['ai-llm-guardrails','AI','Implement LLM safety guardrails. Input validation, output filtering, PII detection, content policy.'],
  ['ai-agent-memory-design','AI','Design memory systems for AI agents. Short-term, long-term, episodic, semantic memory.'],
  ['ai-multi-modal-pipeline','AI','Build pipelines processing text, images, audio, video together with modality alignment.'],
  ['ai-reinforcement-learning-gym','AI','Train RL agents using custom Gym environments with reward shaping and curriculum learning.'],
  ['ai-speech-to-action','AI','Convert speech commands to executable actions with intent recognition and slot filling.'],
  ['ai-document-intelligence','AI','Extract structured data from PDFs, forms, invoices using OCR and layout analysis.'],
  ['ai-conversational-flow-designer','AI','Design conversational flows with branching logic, context management, and fallback handling.'],
  ['ai-anomaly-detection-realtime','AI','Detect anomalies in real-time data streams using statistical methods and autoencoders.'],
  ['ai-embedding-fine-tuning','AI','Fine-tune embedding models for domain-specific similarity search and retrieval tasks.'],
  ['ai-knowledge-graph-builder','AI','Build knowledge graphs from unstructured text using NER, relation extraction, and entity linking.'],
  ['ai-model-serving-triton','AI','Serve ML models at scale with NVIDIA Triton. Covers model ensembles, dynamic batching, and GPU scheduling.'],
  ['ai-text-classification-pipeline','AI','Build text classification pipelines from labeling to deployment with active learning.'],
  ['ai-image-segmentation','AI','Implement image segmentation models. Covers semantic, instance, and panoptic segmentation.'],
  ['cloud-cost-anomaly-detector','Cloud','Detect unexpected cloud cost spikes with ML-based anomaly detection and Slack alerts.'],
  ['cloud-multi-region-failover','Cloud','Design multi-region failover with DNS failover, DB replication, and session persistence.'],
  ['cloud-spot-instance-optimizer','Cloud','Optimize costs using spot/preemptible instances with bidding strategies and interruption handling.'],
  ['cloud-finops-dashboard','Cloud','Build FinOps dashboards for cost visibility with tagging strategies and recommendations.'],
  ['cloud-service-mesh-design','Cloud','Design service mesh with Istio/Linkerd. Traffic management, mTLS, observability.'],
  ['cloud-serverless-orchestration','Cloud','Orchestrate serverless workflows with Step Functions covering saga patterns and fan-out.'],
  ['cloud-edge-computing-patterns','Cloud','Deploy computation at the edge with CloudFlare Workers and Lambda@Edge.'],
  ['cloud-kubernetes-cost-optimization','Cloud','Optimize Kubernetes costs with right-sizing, spot nodes, and cluster autoscaling.'],
  ['cloud-disaster-recovery-planning','Cloud','Plan disaster recovery strategies. RTO/RPO targets, backup automation, and failover testing.'],
  ['cloud-hybrid-cloud-connectivity','Cloud','Connect on-premises and cloud environments with VPN, Direct Connect, and transit gateways.'],
  ['security-supply-chain-hardening','Security','Harden software supply chains with SBOM, dependency pinning, and SLSA provenance.'],
  ['security-zero-trust-implementation','Security','Implement zero trust end-to-end. Identity verification, micro-segmentation, continuous validation.'],
  ['security-secrets-rotation-automation','Security','Automate secrets rotation for databases, APIs, and certificates with Vault integration.'],
  ['security-container-scanning','Security','Scan container images with Trivy, Grype, and Snyk. Base image selection and remediation.'],
  ['security-api-rate-limiting','Security','Sophisticated API rate limiting with sliding window, token bucket, and distributed Redis.'],
  ['security-waf-rule-engineering','Security','Engineer custom WAF rules for ModSecurity, AWS WAF, and CloudFlare with tuning.'],
  ['security-incident-automation','Security','Automate incident response with alert triage, evidence collection, and containment.'],
  ['security-code-signing','Security','Code signing for apps and packages. GPG, Sigstore, notarization, CI/CD integration.'],
  ['security-runtime-protection','Security','Runtime protection with Falco, AppArmor, seccomp profiles, and eBPF monitoring.'],
  ['security-oauth2-hardening','Security','Harden OAuth2/OIDC. PKCE, token binding, DPoP, refresh token rotation.'],
  ['security-cors-configuration','Security','Configure CORS correctly for APIs and microservices with security best practices.'],
  ['security-csp-implementation','Security','Implement Content Security Policy headers to prevent XSS and data injection attacks.'],
  ['security-certificate-pinning','Security','Implement certificate pinning for mobile and web apps to prevent MITM attacks.'],
  ['security-threat-intelligence','Security','Integrate threat intelligence feeds for proactive security monitoring and blocking.'],
  ['security-devsecops-pipeline','Security','Build DevSecOps pipelines with SAST, DAST, SCA, and container scanning in CI.'],
  ['frontend-micro-frontend-federation','Frontend','Build micro-frontends with Module Federation. Shared deps, runtime integration.'],
  ['frontend-server-components-patterns','Frontend','Advanced React Server Components. Streaming, suspense, server actions.'],
  ['frontend-web-vitals-optimization','Frontend','Optimize Core Web Vitals. LCP, FID, CLS with image and font optimization.'],
  ['frontend-design-tokens-system','Frontend','Build design token systems. Token taxonomy, multi-platform output, theme switching.'],
  ['frontend-animation-orchestration','Frontend','Orchestrate complex UI animations with Framer Motion, GSAP, and scroll-driven animations.'],
  ['frontend-form-wizard-builder','Frontend','Build multi-step form wizards with validation, persistence, and conditional steps.'],
  ['frontend-data-grid-advanced','Frontend','High-performance data grids with virtualization, sorting, filtering, and pagination.'],
  ['frontend-pwa-push-notifications','Frontend','PWA push notifications with service workers, VAPID keys, and click handling.'],
  ['frontend-state-machine-ui','Frontend','Model UI state with XState state machines. Complex flows, guards, and actions.'],
  ['frontend-accessibility-testing-automation','Frontend','Automate accessibility testing in CI with axe-core, pa11y, and lighthouse.'],
  ['frontend-component-testing-storybook','Frontend','Test UI components in Storybook with visual regression, interaction testing, and docs.'],
  ['frontend-css-in-js-patterns','Frontend','CSS-in-JS patterns with styled-components, Emotion, and vanilla-extract for type safety.'],
  ['frontend-image-lazy-loading','Frontend','Implement image lazy loading with intersection observer, blur placeholders, and srcset.'],
  ['frontend-infinite-scroll','Frontend','Build infinite scroll with virtualization, prefetching, and scroll position restoration.'],
  ['frontend-drag-drop-builder','Frontend','Build drag-and-drop interfaces with dnd-kit, smooth animations, and accessible fallbacks.'],
  ['backend-event-driven-architecture','Backend','Design event-driven systems with event sourcing, CQRS, and message brokers.'],
  ['backend-graphql-federation-gateway','Backend','Build federated GraphQL gateways with Apollo Federation and entity resolution.'],
  ['backend-distributed-locking','Backend','Implement distributed locks with Redis Redlock, Zookeeper, and database advisory locks.'],
  ['backend-idempotency-patterns','Backend','Make APIs idempotent with idempotency keys and request deduplication.'],
  ['backend-circuit-breaker-patterns','Backend','Circuit breakers with half-open states, fallback strategies, and bulkhead isolation.'],
  ['backend-api-versioning-strategies','Backend','API versioning with URL, header, and content negotiation approaches.'],
  ['backend-webhook-delivery-system','Backend','Reliable webhook delivery with retry, exponential backoff, and dead letter queues.'],
  ['backend-job-queue-design','Backend','Design job queues with priority, delayed jobs, rate limiting, and monitoring.'],
  ['backend-database-sharding-strategies','Backend','Database sharding with hash-based, range-based, and directory-based strategies.'],
  ['backend-caching-strategies-advanced','Backend','Advanced caching with invalidation, write-through, stampede prevention, multi-tier.'],
  ['backend-connection-pooling','Backend','Database connection pooling optimization with PgBouncer, ProxySQL, and app-level pools.'],
  ['backend-request-validation','Backend','Input validation with Zod, Joi, or class-validator. Request sanitization and error formatting.'],
  ['backend-file-upload-processing','Backend','Handle file uploads with streaming, chunked uploads, virus scanning, and cloud storage.'],
  ['backend-pagination-strategies','Backend','Implement cursor-based and offset pagination with consistent ordering and total counts.'],
  ['backend-health-check-patterns','Backend','Design health check endpoints. Liveness, readiness, startup probes with dependency checks.'],
  ['data-lakehouse-architecture','Data','Design data lakehouse with Delta Lake, Iceberg, and unified batch/streaming.'],
  ['data-real-time-streaming-pipeline','Data','Build real-time streaming with Kafka Streams and Flink with exactly-once.'],
  ['data-quality-monitoring','Data','Monitor data quality with Great Expectations, dbt tests, and anomaly detection.'],
  ['data-reverse-etl','Data','Reverse ETL to sync warehouse data to SaaS tools with Census patterns.'],
  ['data-feature-engineering-advanced','Data','Advanced feature engineering with temporal features, embeddings, and automated selection.'],
  ['data-data-catalog-implementation','Data','Data catalogs with DataHub and Amundsen for discovery and governance.'],
  ['data-change-data-capture-patterns','Data','CDC with Debezium, DynamoDB Streams, and PostgreSQL logical replication.'],
  ['data-data-mesh-implementation','Data','Data mesh with domain ownership, data products, and federated governance.'],
  ['data-dimensional-modeling','Data','Dimensional models with star schemas, SCDs, conformed dimensions, and fact tables.'],
  ['data-data-lineage-tracking','Data','End-to-end data lineage with column-level tracking and impact analysis.'],
  ['data-data-warehouse-design','Data','Design data warehouses with Snowflake/BigQuery. Covers partitioning, clustering, and materialized views.'],
  ['data-event-streaming-kafka','Data','Build event streaming with Apache Kafka. Covers topics, partitions, consumer groups, and exactly-once.'],
  ['data-data-governance-framework','Data','Implement data governance frameworks with policies, stewardship, and quality metrics.'],
  ['data-time-series-database','Data','Design time-series data storage with TimescaleDB, InfluxDB, or Prometheus for IoT and metrics.'],
  ['data-graph-database-patterns','Data','Graph database patterns with Neo4j. Covers modeling, Cypher queries, and graph algorithms.'],
  ['mobile-offline-first-architecture','Mobile','Offline-first mobile apps with local databases, sync, and conflict resolution.'],
  ['mobile-push-notification-architecture','Mobile','Push notification systems with FCM/APNs, segmentation, and analytics.'],
  ['mobile-app-performance-profiling','Mobile','Profile mobile performance. CPU, memory, battery, network, frame rate.'],
  ['mobile-ci-cd-fastlane-advanced','Mobile','Advanced mobile CI/CD with Fastlane match, screenshots, and App Store.'],
  ['mobile-deep-linking-advanced','Mobile','Deep linking with universal links, deferred deep links, and attribution.'],
  ['mobile-biometric-authentication','Mobile','Implement biometric auth with Face ID, Touch ID, and fingerprint on Android.'],
  ['mobile-background-processing','Mobile','Background processing patterns for mobile apps. WorkManager, BGTasks, and sync strategies.'],
  ['mobile-app-size-optimization','Mobile','Optimize mobile app size with asset compression, code shrinking, and on-demand delivery.'],
  ['mobile-crash-analytics','Mobile','Implement crash analytics with Crashlytics, Sentry. Symbolication and trend analysis.'],
  ['mobile-in-app-purchases','Mobile','Implement in-app purchases for iOS and Android with receipt validation and subscription management.'],
  ['testing-contract-testing-pact','Testing','Consumer-driven contract testing with Pact. Provider verification and broker setup.'],
  ['testing-chaos-engineering','Testing','Chaos engineering with Chaos Monkey, Litmus, and hypothesis-driven experiments.'],
  ['testing-load-testing-artillery','Testing','Load testing with Artillery. Scenario scripting, ramp-up patterns, and CI integration.'],
  ['testing-visual-regression-percy','Testing','Visual regression with Percy/Chromatic. Snapshot strategies and approval workflows.'],
  ['testing-api-fuzzing-advanced','Testing','API fuzzing with property-based testing, grammar-based fuzzing, and mutation testing.'],
  ['testing-performance-benchmarking','Testing','Code performance benchmarking with statistical analysis and regression detection.'],
  ['testing-test-data-management','Testing','Test data with factories, fixtures, database seeding, and data masking.'],
  ['testing-mutation-testing','Testing','Mutation testing with Stryker and PIT for test suite quality validation.'],
  ['testing-snapshot-testing','Testing','Snapshot testing patterns for UI components, API responses, and data structures.'],
  ['testing-end-to-end-cypress','Testing','E2E testing with Cypress. Custom commands, fixtures, network stubbing, and CI integration.'],
  ['sre-error-budget-management','SRE','Manage error budgets with SLO definition, burn rate alerts, and policies.'],
  ['sre-capacity-planning','SRE','Plan infrastructure capacity with demand forecasting and scaling strategies.'],
  ['sre-postmortem-culture','SRE','Build blameless postmortem culture with incident analysis and action tracking.'],
  ['sre-on-call-management','SRE','Design on-call rotations with escalation policies, runbooks, and fatigue prevention.'],
  ['sre-toil-elimination','SRE','Identify and eliminate toil through automation, self-service, and process improvement.'],
  ['devops-gitops-advanced','DevOps','Advanced GitOps with ArgoCD/Flux. Multi-cluster, progressive delivery, drift detection.'],
  ['devops-platform-engineering','DevOps','Build internal developer platforms with Backstage, golden paths, and self-service.'],
  ['devops-observability-stack','DevOps','Complete observability with Prometheus metrics, Loki logs, Tempo traces.'],
  ['devops-incident-management','DevOps','Automate incident management with PagerDuty, escalation, and war rooms.'],
  ['devops-deployment-strategies','DevOps','Blue-green, canary, rolling, A/B deployments with feature flags.'],
  ['devops-container-orchestration','DevOps','Container orchestration patterns beyond basic Kubernetes. StatefulSets, operators, and CRDs.'],
  ['devops-infrastructure-testing','DevOps','Test infrastructure code with Terratest, Kitchen-Terraform, and policy-as-code.'],
  ['devops-log-management','DevOps','Design log management systems with collection, parsing, storage, and retention policies.'],
  ['devops-secrets-management','DevOps','Manage secrets across environments with Vault, AWS Secrets Manager, and rotation automation.'],
  ['devops-service-catalog','DevOps','Build service catalogs for developer self-service. Covers templates, provisioning, and lifecycle.'],
  ['web3-smart-contract-upgrades','Web3','Upgradeable smart contracts with proxy patterns, storage layouts, and migrations.'],
  ['web3-defi-yield-aggregator','Web3','DeFi yield aggregators with strategy contracts, vaults, and auto-compounding.'],
  ['web3-nft-marketplace-backend','Web3','NFT marketplace backends with metadata standards, royalties, and lazy minting.'],
  ['web3-cross-chain-messaging','Web3','Cross-chain messaging with LayerZero, Wormhole, and bridge security.'],
  ['web3-dao-governance-contracts','Web3','DAO governance with Governor contracts, timelock, vote delegation.'],
  ['web3-token-vesting','Web3','Token vesting contracts with cliff periods, linear/cliff schedules, and revocation.'],
  ['web3-gasless-transactions','Web3','Implement gasless transactions with meta-transactions, relayers, and EIP-2771.'],
  ['web3-merkle-airdrop','Web3','Build merkle tree airdrops for efficient token distribution with proof verification.'],
  ['web3-on-chain-analytics','Web3','Build on-chain analytics dashboards with indexed data from The Graph and Dune.'],
  ['web3-wallet-connect-integration','Web3','Integrate WalletConnect for multi-wallet support across mobile and desktop.'],
  ['product-analytics-implementation','Business','Product analytics from scratch. Event taxonomy, funnels, and cohort tracking.'],
  ['product-experimentation-platform','Business','Build experimentation platforms with A/B testing and statistical engines.'],
  ['product-onboarding-optimization','Business','Optimize onboarding with activation metrics, progressive disclosure, and tooltips.'],
  ['product-notification-system-design','Business','Design notification systems with multi-channel delivery and preferences.'],
  ['product-search-implementation','Business','Product search with Elasticsearch/Algolia, facets, autocomplete, and relevance.'],
  ['product-recommendation-system','Business','Build recommendation systems with collaborative filtering, content-based, and hybrid approaches.'],
  ['product-billing-integration','Business','Integrate billing with Stripe/Paddle. Subscriptions, metered usage, and invoicing.'],
  ['product-waitlist-management','Business','Build waitlist systems with referral bonuses, priority scoring, and drip campaigns.'],
  ['product-user-feedback-system','Business','Build user feedback systems with surveys, NPS, feature voting, and sentiment analysis.'],
  ['product-pricing-page-optimization','Business','Optimize pricing pages with psychological pricing, plan comparison, and CTAs.'],
  ['writing-technical-blog-posts','Writing','Write compelling technical blog posts with structure, code examples, and SEO.'],
  ['writing-api-documentation','Writing','Excellent API docs with OpenAPI specs, code examples, and error reference.'],
  ['writing-release-notes-generator','Writing','Generate release notes from git history with conventional commits.'],
  ['writing-rfc-template','Writing','Write technical RFCs with problem statement, solution, alternatives, and plan.'],
  ['writing-incident-report','Writing','Write incident reports with timeline, root cause, impact, and action items.'],
  ['writing-architecture-decision-record','Writing','Write ADRs documenting architectural decisions, context, consequences, and alternatives.'],
  ['writing-runbook-template','Writing','Write operational runbooks with step-by-step procedures and escalation paths.'],
  ['writing-code-review-feedback','Writing','Write constructive code review feedback that teaches and improves code quality.'],
  ['writing-technical-proposal','Writing','Write technical proposals for new projects with scope, timeline, and risk assessment.'],
  ['writing-postmortem-template','Writing','Write postmortem reports with 5-whys analysis, timeline, and prevention measures.'],
  ['game-ecs-architecture','Game','Entity Component System architecture with data-oriented design and system scheduling.'],
  ['game-procedural-world-generation','Game','Procedural world generation with noise functions, biomes, and terrain systems.'],
  ['game-multiplayer-netcode','Game','Multiplayer networking with client prediction, server reconciliation, and lag compensation.'],
  ['game-shader-effects','Game','Visual shader effects for water, fire, fog, bloom in GLSL/HLSL.'],
  ['game-dialogue-system','Game','Branching dialogue systems with condition checks, variables, and localization.'],
  ['game-inventory-system','Game','Game inventory systems with stacking, categories, drag-drop, and persistence.'],
  ['game-save-system','Game','Game save systems with serialization, versioning, cloud sync, and migration.'],
  ['game-ai-behavior-trees','Game','AI behavior trees for NPCs with composite nodes, decorators, and blackboards.'],
  ['game-particle-system','Game','Particle systems for visual effects. Emitters, forces, collision, and LOD management.'],
  ['game-audio-system','Game','Game audio systems with spatial audio, music layering, and dynamic mixing.'],
  ['iot-sensor-data-pipeline','IoT','IoT sensor data pipelines with MQTT, time-series storage, and alerting.'],
  ['iot-edge-ml-deployment','IoT','Deploy ML on edge with TensorFlow Lite, ONNX Runtime, and OTA updates.'],
  ['iot-device-provisioning','IoT','Automate IoT device provisioning with zero-touch enrollment and fleet management.'],
  ['iot-digital-twin-implementation','IoT','Digital twins with state sync, simulation, and predictive maintenance.'],
  ['iot-firmware-ota-updates','IoT','Implement firmware OTA updates with delta updates, rollback, and A/B partitions.'],
  ['iot-protocol-design','IoT','Design IoT communication protocols. MQTT, CoAP, WebSocket with security and efficiency.'],
  ['iot-time-series-analytics','IoT','Analyze IoT time-series data with downsampling, aggregation, and anomaly detection.'],
  ['workflow-approval-system','Workflow','Approval workflows with multi-level approvals, delegation, and audit trails.'],
  ['workflow-document-processing','Workflow','Document processing with OCR, classification, extraction, and routing.'],
  ['workflow-email-automation-advanced','Workflow','Advanced email automation with drip campaigns, triggers, and deliverability.'],
  ['workflow-report-generation','Workflow','Automated report generation with aggregation, templates, PDF, and scheduling.'],
  ['workflow-task-orchestration','Workflow','Complex task orchestration with Temporal, dependency management, and recovery.'],
  ['architecture-clean-architecture','Architecture','Clean Architecture with dependency inversion, use cases, and entities.'],
  ['architecture-hexagonal-ports-adapters','Architecture','Hexagonal Architecture with ports, adapters, and domain isolation.'],
  ['architecture-strangler-fig-migration','Architecture','Migrate monoliths with Strangler Fig. Incremental extraction and routing.'],
  ['architecture-saga-pattern','Architecture','Distributed transactions with Sagas. Choreography vs orchestration.'],
  ['architecture-outbox-pattern','Architecture','Transactional Outbox for reliable event publishing with CDC.'],
  ['architecture-cqrs-pattern','Architecture','CQRS pattern separating read and write models for optimal scaling.'],
  ['architecture-event-sourcing','Architecture','Event sourcing with event stores, projections, snapshots, and replay.'],
  ['architecture-modular-monolith','Architecture','Modular monolith architecture with bounded contexts and clear module boundaries.'],
  ['architecture-domain-events','Architecture','Domain events for decoupled communication between bounded contexts.'],
  ['architecture-api-composition','Architecture','API composition pattern for aggregating data from multiple microservices.'],
  ['observability-distributed-tracing','Observability','Distributed tracing with OpenTelemetry, context propagation, and sampling.'],
  ['observability-custom-metrics','Observability','Custom application metrics with RED/USE methods and cardinality management.'],
  ['observability-log-aggregation','Observability','Log aggregation with structured logging, shipping, and trace correlation.'],
  ['observability-alerting-strategy','Observability','Effective alerting with fatigue prevention and symptom-based alerts.'],
  ['observability-dashboards-design','Observability','Monitoring dashboards with layout principles and actionable visualizations.'],
  ['performance-database-query-optimization','Performance','Query optimization with EXPLAIN analysis, indexes, and connection pooling.'],
  ['performance-nodejs-profiling','Performance','Node.js profiling with CPU, memory, event loop, and flame graphs.'],
  ['performance-web-bundle-optimization','Performance','Web bundle optimization with code splitting, tree shaking, and lazy loading.'],
  ['performance-cdn-optimization','Performance','CDN optimization with cache headers, purge strategies, and edge computing.'],
  ['performance-api-response-optimization','Performance','API optimization with pagination, field selection, and response caching.'],
  ['auth-passwordless-implementation','Auth','Passwordless auth with magic links, WebAuthn/passkeys, and biometrics.'],
  ['auth-multi-tenant-rbac','Auth','Multi-tenant RBAC with role hierarchies and resource-based permissions.'],
  ['auth-session-management','Auth','Secure session management with storage, rotation, and distributed sessions.'],
  ['auth-social-login-integration','Auth','Social login with Google, GitHub, Apple and account linking.'],
  ['auth-api-key-management','Auth','API key management with generation, rotation, rate limiting, and analytics.'],
  ['networking-websocket-scaling','Networking','Scale WebSockets with sticky sessions, pub/sub backends, and reconnection.'],
  ['networking-grpc-service-design','Networking','gRPC services with protobuf, streaming, error handling, and load balancing.'],
  ['networking-api-gateway-patterns','Networking','API gateway with routing, auth, rate limiting, and response transformation.'],
  ['networking-dns-architecture','Networking','DNS architecture with failover, GeoDNS, and service discovery.'],
  ['compliance-gdpr-implementation','Compliance','GDPR compliance with consent, data subject rights, and breach notification.'],
  ['compliance-hipaa-safeguards','Compliance','HIPAA safeguards with PHI encryption, access controls, and audit logging.'],
  ['compliance-soc2-preparation','Compliance','SOC 2 preparation with trust services criteria and evidence collection.'],
  ['compliance-pci-dss-implementation','Compliance','PCI DSS with cardholder data protection and network segmentation.'],
  ['dx-monorepo-tooling','DX','Monorepo tooling with Turborepo/Nx, task pipelines, and remote caching.'],
  ['dx-developer-onboarding','DX','Developer onboarding with dev environment setup, docs, and mentorship.'],
  ['dx-code-generation-templates','DX','Code generation with templates, scaffolding, and custom generators.'],
  ['dx-linting-formatting-setup','DX','Linting and formatting with ESLint, Prettier, commitlint, and pre-commit hooks.'],
  ['dx-local-development-environment','DX','Local dev with Docker Compose, env vars, seed data, and hot reloading.'],
  ['dx-inner-source-practices','DX','Inner source practices for cross-team collaboration with contribution guidelines.'],
  ['dx-api-mocking','DX','API mocking with MSW, Prism, and WireMock for frontend development and testing.'],
  ['dx-documentation-as-code','DX','Documentation as code with Docusaurus, MkDocs, and CI/CD publishing.'],
];

// ===== NEW AGENTS =====
const agentDefs = [
  ['ai-pair-programmer','AI pair programmer that writes code alongside you, suggests implementations, and catches bugs.'],
  ['architecture-reviewer','Reviews system architecture for scalability, reliability, cost. Identifies bottlenecks.'],
  ['api-design-reviewer','Reviews API designs for consistency, usability, and REST/GraphQL best practices.'],
  ['dependency-auditor','Audits dependencies for vulnerabilities, license issues, and outdated packages.'],
  ['migration-planner','Plans database and framework migrations with step-by-step rollback strategies.'],
  ['performance-profiler','Profiles performance, identifies bottlenecks, memory leaks, and optimization opportunities.'],
  ['test-coverage-analyzer','Analyzes test coverage gaps and suggests critical tests to add.'],
  ['error-pattern-detector','Detects recurring error patterns and suggests systematic fixes.'],
  ['accessibility-auditor','Audits for accessibility compliance against WCAG guidelines.'],
  ['cost-optimizer-agent','Optimizes cloud costs with rightsizing and reserved instance recommendations.'],
  ['compliance-checker','Checks for GDPR, HIPAA, SOC 2, and PCI DSS compliance violations.'],
  ['documentation-generator','Generates comprehensive documentation from code with API docs and diagrams.'],
  ['refactoring-advisor','Advises on refactoring opportunities, code smells, and effort estimates.'],
  ['incident-response-agent','Assists during production incidents with diagnosis and mitigation.'],
  ['release-manager-agent','Manages releases with changelogs, version bumps, and rollback plans.'],
  ['schema-designer','Designs database schemas optimized for query patterns with index suggestions.'],
  ['security-scanner-agent','Continuously scans for security vulnerabilities in deps, configs, and code.'],
  ['devops-automator','Automates DevOps tasks: CI/CD, monitoring, alerting, and infrastructure.'],
  ['data-pipeline-builder','Builds and optimizes data pipelines for ETL, streaming, and batch.'],
  ['ux-reviewer','Reviews UI/UX for usability, accessibility, responsiveness, and consistency.'],
  ['tech-debt-tracker','Tracks and prioritizes technical debt with categorization and remediation order.'],
  ['onboarding-assistant','Helps new developers onboard by explaining architecture and conventions.'],
  ['code-quality-guardian','Guards code quality with conventions, complexity limits, and documentation.'],
  ['integration-tester','Designs integration tests for API contracts and service interactions.'],
  ['feature-flag-manager','Manages feature flag lifecycle with targeting, rollouts, and cleanup.'],
  ['monitoring-setup-agent','Sets up monitoring with dashboards, alerts, and SLOs.'],
  ['database-tuner','Tunes database performance with query analysis and config optimization.'],
  ['log-analyzer','Analyzes logs for patterns, anomalies, and cross-service event correlation.'],
  ['chaos-engineer-agent','Plans chaos experiments to test system resilience.'],
  ['sprint-retrospective-facilitator','Facilitates sprint retros with feedback gathering and action items.'],
  ['api-gateway-architect','Designs API gateway architectures with routing, auth, and rate limiting.'],
  ['frontend-performance-agent','Optimizes frontend performance. Core Web Vitals, bundle size, render patterns.'],
  ['backend-scalability-agent','Analyzes and improves backend scalability. Caching, sharding, async processing.'],
  ['data-quality-agent','Monitors and improves data quality with validation rules and anomaly detection.'],
  ['cloud-migration-agent','Plans and executes cloud migrations with minimal downtime.'],
  ['container-security-agent','Scans and hardens container deployments. Image scanning, runtime security.'],
  ['ml-ops-agent','Manages ML operations including training, deployment, monitoring, and retraining.'],
  ['technical-writer-agent','Writes and maintains technical documentation, ADRs, and runbooks.'],
  ['project-health-agent','Monitors project health metrics: velocity, quality, debt, and team satisfaction.'],
  ['dependency-update-agent','Manages dependency updates with compatibility testing and automated PRs.'],
];

// ===== NEW COMMANDS =====
const cmdDefs = [
  ['profile-performance','Profile application performance and identify bottlenecks with recommendations.'],
  ['scan-vulnerabilities','Scan codebase for security vulnerabilities in dependencies, configs, and code.'],
  ['generate-api-docs','Generate OpenAPI documentation from code annotations and route definitions.'],
  ['analyze-bundle','Analyze JavaScript bundle size and suggest code splitting opportunities.'],
  ['check-accessibility','Run accessibility audit against WCAG guidelines and report violations.'],
  ['lint-docker','Lint Dockerfiles for best practices including caching, security, and size.'],
  ['validate-schema','Validate database schema for normalization, indexing, and query performance.'],
  ['estimate-cost','Estimate cloud infrastructure costs based on architecture and usage.'],
  ['generate-changelog','Generate changelog from git commits following conventional commit format.'],
  ['scaffold-microservice','Scaffold a new microservice with standard structure, CI/CD, and monitoring.'],
  ['setup-monitoring','Set up application monitoring with metrics, logging, and alerting.'],
  ['create-migration','Create database migration files with up/down scripts and validation.'],
  ['audit-dependencies','Audit dependencies for vulnerabilities, licenses, and available updates.'],
  ['generate-tests','Generate unit and integration tests for uncovered code paths.'],
  ['optimize-queries','Analyze and optimize database queries with EXPLAIN and index suggestions.'],
  ['setup-ci-pipeline','Set up CI pipeline with build, test, lint, and deploy stages.'],
  ['create-env-template','Create environment variable template with documentation and validation.'],
  ['scaffold-api-endpoint','Scaffold a new API endpoint with handler, validation, tests, and docs.'],
  ['run-security-audit','Run comprehensive security audit with SAST, dependency check, and config.'],
  ['generate-types','Generate TypeScript types from API schemas, database models, or JSON.'],
  ['setup-feature-flags','Set up feature flag infrastructure with provider integration.'],
  ['create-data-seed','Create database seed scripts with realistic test data.'],
  ['validate-environment','Validate environment configuration against schema with error messages.'],
  ['setup-error-tracking','Set up error tracking with source maps and alert configuration.'],
  ['scaffold-react-component','Scaffold React component with props, types, tests, and stories.'],
  ['run-load-test','Run load tests against API endpoints and generate reports.'],
  ['create-backup-plan','Create database backup strategy with scheduling and retention.'],
  ['setup-rate-limiter','Set up API rate limiting with configurable windows and limits.'],
  ['generate-er-diagram','Generate entity-relationship diagrams from database schema.'],
  ['scaffold-background-worker','Scaffold background worker/job processor with queue and monitoring.'],
  ['check-code-quality','Run comprehensive code quality analysis with complexity and duplication metrics.'],
  ['generate-openapi-spec','Generate OpenAPI 3.0 spec from existing route handlers and middleware.'],
  ['setup-git-hooks','Set up git hooks with pre-commit linting, commit message validation, and pre-push tests.'],
  ['analyze-dependencies','Analyze dependency tree for unused, duplicate, and heavy packages.'],
  ['scaffold-test-suite','Scaffold test suite for a module with unit, integration, and e2e tests.'],
  ['generate-docker-compose','Generate Docker Compose configuration for local development environment.'],
  ['check-type-safety','Run comprehensive type checking with strict TypeScript configuration.'],
  ['setup-logging','Set up structured logging with correlation IDs and log levels.'],
  ['create-index-strategy','Analyze queries and create optimal database index strategy.'],
  ['scaffold-cli-tool','Scaffold a CLI tool with argument parsing, help text, and completion.'],
];

// Generate skills with Claude Code content
const newSkills = [];
skillDefs.forEach(([id, cat, desc]) => {
  const title = id.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
  newSkills.push({
    id,
    d: desc,
    c: `---\nname: ${id}\ndescription: "${desc.replace(/"/g, "'")}"\ncategory: ${cat.toLowerCase()}\nrisk: safe\nsource: claude-generated\ndate_added: "2026-03-20"\ntags:\n- ${cat.toLowerCase()}\n- claude-code\ntools:\n- claude-code\n- cursor\n---\n\n# ${title}\n\n## Overview\n\n${desc}\n\n## When to Use\n\n- When working on ${cat.toLowerCase()} projects\n- When you need expert guidance on ${id.replace(/-/g, ' ')}\n- When implementing best practices for ${cat.toLowerCase()} development\n\n## Best Practices\n\n- Follow industry standards and conventions\n- Write clean, maintainable, well-documented code\n- Include comprehensive tests\n- Consider performance, security, and scalability\n- Use proper error handling and logging\n`
  });
});

const newAgents = [];
agentDefs.forEach(([id, desc]) => {
  const title = id.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
  newAgents.push({
    id,
    d: desc,
    c: `---\nname: ${id}\ndescription: "${desc.replace(/"/g, "'")}"\ntype: agent\nsource: claude-generated\ndate_added: "2026-03-20"\ntools:\n- claude-code\n- cursor\n---\n\n# ${title}\n\n## Role\n\n${desc}\n\n## Capabilities\n\n- Analyzes code and project context\n- Provides actionable recommendations\n- Follows best practices and industry standards\n- Integrates with Claude Code and Cursor workflows\n`
  });
});

const newCommands = [];
cmdDefs.forEach(([id, desc]) => {
  newCommands.push({
    id,
    d: desc,
    c: `---\nname: ${id}\ndescription: "${desc.replace(/"/g, "'")}"\ntype: command\nsource: claude-generated\ndate_added: "2026-03-20"\ntools:\n- claude-code\n- cursor\n---\n\n# /${id}\n\n## Usage\n\n\`/${id}\`\n\n## Description\n\n${desc}\n\n## What It Does\n\n- Analyzes your current project context\n- Applies best practices and standards\n- Generates actionable output\n- Works with Claude Code and Cursor\n`
  });
});

console.log('Generated:', newSkills.length, 'skills,', newAgents.length, 'agents,', newCommands.length, 'commands');

// Merge with existing data
const src = fs.readFileSync('src/dashboard-data.js', 'utf8');
const clean = src.replace('window._JARVIS_RAW = ', 'var D = ').replace(/;\s*$/, ';');
const fn = new Function(clean + ' return D;');
const D = fn();
const existingIds = new Set([...D.skills.map(s=>s.id), ...D.agents.map(a=>a.id), ...D.commands.map(c=>c.id)]);

let added = { skills: 0, agents: 0, commands: 0 };
newSkills.forEach(s => { if (!existingIds.has(s.id)) { D.skills.push(s); existingIds.add(s.id); added.skills++; }});
newAgents.forEach(a => { if (!existingIds.has(a.id)) { D.agents.push(a); existingIds.add(a.id); added.agents++; }});
newCommands.forEach(c => { if (!existingIds.has(c.id)) { D.commands.push(c); existingIds.add(c.id); added.commands++; }});

console.log('Added:', added.skills, 'skills,', added.agents, 'agents,', added.commands, 'commands');
console.log('FINAL: Skills:', D.skills.length, 'Agents:', D.agents.length, 'Commands:', D.commands.length);
console.log('TOTAL:', D.skills.length + D.agents.length + D.commands.length);

const output = 'window._JARVIS_RAW = ' + JSON.stringify(D) + ';';
fs.writeFileSync('src/dashboard-data.js', output, 'utf8');
console.log('Written:', (output.length / 1024 / 1024).toFixed(1), 'MB');
