const fs = require('fs');

const src = fs.readFileSync('src/dashboard-data.js', 'utf8');
const clean = src.replace('window._JARVIS_RAW = ', 'var D = ').replace(/;\s*$/, ';');
const fn = new Function(clean + ' return D;');
const D = fn();
const existingIds = new Set([...D.skills.map(s=>s.id), ...D.agents.map(a=>a.id), ...D.commands.map(c=>c.id)]);

function mk(type, id, cat, desc) {
  if (existingIds.has(id)) return null;
  existingIds.add(id);
  const title = id.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');
  const safeDesc = desc.replace(/"/g, "'");
  let content;
  if (type === 'skill') {
    content = `---\nname: ${id}\ndescription: "${safeDesc}"\ncategory: ${cat.toLowerCase()}\nrisk: safe\nsource: claude-generated\ndate_added: "2026-03-21"\ntags:\n- ${cat.toLowerCase()}\n- claude-code\ntools:\n- claude-code\n- cursor\n---\n\n# ${title}\n\n## Overview\n\n${desc}\n\n## When to Use\n\n- When working on ${cat.toLowerCase()} tasks\n- When you need guidance on ${id.replace(/-/g,' ')}\n\n## Best Practices\n\n- Follow industry standards\n- Write clean tested code\n- Consider security and performance\n`;
  } else if (type === 'agent') {
    content = `---\nname: ${id}\ndescription: "${safeDesc}"\ntype: agent\nsource: claude-generated\ndate_added: "2026-03-21"\ntools:\n- claude-code\n- cursor\n---\n\n# ${title}\n\n## Role\n\n${desc}\n\n## Capabilities\n\n- Analyzes code and project context\n- Provides actionable recommendations\n- Follows best practices\n`;
  } else {
    content = `---\nname: ${id}\ndescription: "${safeDesc}"\ntype: command\nsource: claude-generated\ndate_added: "2026-03-21"\ntools:\n- claude-code\n- cursor\n---\n\n# /${id}\n\n## Usage\n\n\`/${id}\`\n\n## Description\n\n${desc}\n`;
  }
  return { id, d: desc, c: content };
}

const newS = [], newA = [], newC = [];

// === 200+ SKILLS ===
const skills = [
['ai-model-distillation','AI','Distill large models into smaller faster ones with knowledge distillation pruning and quantization'],
['ai-prompt-chain-builder','AI','Build complex prompt chains that decompose tasks into subtasks with conditional branching'],
['ai-synthetic-data-generator','AI','Generate realistic synthetic datasets for ML training with privacy guarantees'],
['ai-model-ab-testing','AI','Run A/B tests between ML models in production with traffic splitting and rollback'],
['ai-feature-store-design','AI','Design feature stores for ML pipelines with online offline serving'],
['ai-vector-search-optimization','AI','Optimize vector similarity search for RAG with HNSW tuning and hybrid strategies'],
['ai-llm-guardrails','AI','Implement safety guardrails for LLM apps with input validation and PII detection'],
['ai-agent-memory-design','AI','Design memory systems for AI agents with short-term long-term and episodic memory'],
['ai-multi-modal-pipeline','AI','Build pipelines processing text images audio video with modality fusion'],
['ai-document-intelligence','AI','Extract structured data from PDFs forms invoices using OCR and NER'],
['ai-anomaly-detection-realtime','AI','Detect anomalies in real-time data streams with adaptive thresholding'],
['ai-conversational-flow-designer','AI','Design conversational flows with branching logic and fallback handling'],
['ai-knowledge-graph-builder','AI','Build knowledge graphs from unstructured text with entity extraction'],
['ai-speech-to-action','AI','Convert speech commands to executable actions with intent recognition'],
['ai-reinforcement-learning-gym','AI','Train RL agents using custom Gym environments with reward shaping'],
['cloud-cost-anomaly-detector','Cloud','Detect unexpected cloud cost spikes with ML-based anomaly detection'],
['cloud-multi-region-failover','Cloud','Design multi-region failover with DNS failover and database replication'],
['cloud-spot-instance-optimizer','Cloud','Optimize costs using spot instances with bidding and interruption handling'],
['cloud-finops-dashboard','Cloud','Build FinOps dashboards for cost visibility with tagging strategies'],
['cloud-serverless-orchestration','Cloud','Orchestrate serverless workflows with Step Functions and saga patterns'],
['cloud-edge-computing-patterns','Cloud','Deploy computation at edge with CloudFlare Workers and Lambda Edge'],
['cloud-service-mesh-design','Cloud','Design service mesh with Istio Linkerd for traffic and observability'],
['cloud-container-orchestration-advanced','Cloud','Advanced container orchestration with custom operators and CRDs'],
['cloud-disaster-recovery-automation','Cloud','Automate disaster recovery with RTO RPO planning and failover testing'],
['cloud-infrastructure-drift-detection','Cloud','Detect infrastructure drift between desired and actual state'],
['security-supply-chain-hardening','Security','Harden supply chains with SBOM generation and SLSA provenance'],
['security-zero-trust-implementation','Security','Implement zero trust with identity verification and micro-segmentation'],
['security-secrets-rotation-automation','Security','Automate secrets rotation for databases APIs and certificates'],
['security-container-scanning','Security','Scan container images for vulnerabilities with Trivy and Grype'],
['security-api-rate-limiting','Security','Implement API rate limiting with sliding window and token bucket'],
['security-waf-rule-engineering','Security','Engineer custom WAF rules with false positive tuning'],
['security-incident-automation','Security','Automate incident response with alert triage and containment'],
['security-code-signing','Security','Implement code signing with GPG Sigstore and CI CD integration'],
['security-runtime-protection','Security','Deploy RASP with Falco AppArmor and eBPF monitoring'],
['security-oauth2-hardening','Security','Harden OAuth2 OIDC with PKCE token binding and rotation'],
['security-threat-intelligence-feeds','Security','Integrate threat intelligence with STIX TAXII and IOC enrichment'],
['security-devsecops-scanning','Security','Integrate security scanning in CI CD with SAST DAST SCA'],
['security-network-segmentation','Security','Design network segmentation with micro-segmentation and VLANs'],
['security-log-correlation','Security','Correlate security logs for threat detection with SIEM'],
['security-compliance-as-code','Security','Implement compliance as code with OPA and automated audit evidence'],
['frontend-micro-frontend-federation','Frontend','Build micro-frontends with Module Federation for independent deployment'],
['frontend-server-components-patterns','Frontend','Advanced React Server Components with streaming and suspense'],
['frontend-web-vitals-optimization','Frontend','Optimize Core Web Vitals LCP FID CLS with image and font loading'],
['frontend-design-tokens-system','Frontend','Build design token systems with multi-platform output and themes'],
['frontend-animation-orchestration','Frontend','Orchestrate UI animations with Framer Motion GSAP and scroll-driven'],
['frontend-form-wizard-builder','Frontend','Build multi-step form wizards with validation and persistence'],
['frontend-data-grid-advanced','Frontend','Build high-performance data grids with virtualization and sorting'],
['frontend-pwa-push-notifications','Frontend','Implement PWA push notifications with service workers and VAPID'],
['frontend-state-machine-ui','Frontend','Model UI state with XState state machines for complex flows'],
['frontend-accessibility-testing-automation','Frontend','Automate accessibility testing with axe-core and lighthouse'],
['frontend-island-architecture','Frontend','Implement islands architecture for partial hydration'],
['frontend-skeleton-loading-patterns','Frontend','Build skeleton loading screens matching real content layout'],
['frontend-infinite-scroll-virtualization','Frontend','Implement infinite scroll with virtualization for large datasets'],
['frontend-drag-drop-builder','Frontend','Build drag and drop interfaces with DnD Kit for sortable lists'],
['frontend-real-time-collaboration-ui','Frontend','Build collaborative UIs with CRDTs and presence indicators'],
['backend-event-driven-architecture','Backend','Design event-driven systems with event sourcing CQRS and Kafka'],
['backend-graphql-federation-gateway','Backend','Build federated GraphQL gateways with Apollo Federation'],
['backend-distributed-locking','Backend','Implement distributed locks with Redis Redlock and Zookeeper'],
['backend-idempotency-patterns','Backend','Make APIs idempotent with idempotency keys and exactly-once'],
['backend-circuit-breaker-patterns','Backend','Implement circuit breakers with fallbacks and bulkhead isolation'],
['backend-api-versioning-strategies','Backend','API versioning with URL header and content negotiation'],
['backend-webhook-delivery-system','Backend','Build reliable webhooks with retry exponential backoff and DLQ'],
['backend-job-queue-design','Backend','Design job queues with priority delayed jobs and rate limiting'],
['backend-database-sharding-strategies','Backend','Implement sharding with hash-based range-based strategies'],
['backend-caching-strategies-advanced','Backend','Advanced caching with invalidation write-through and stampede prevention'],
['backend-connection-pooling-advanced','Backend','Advanced connection pooling with PgBouncer and dynamic sizing'],
['backend-request-deduplication','Backend','Deduplicate requests with request coalescing and cache-aside'],
['backend-graceful-shutdown','Backend','Implement graceful shutdown with connection draining and health checks'],
['backend-multi-tenant-isolation','Backend','Design multi-tenant with schema isolation and row-level security'],
['backend-long-running-tasks','Backend','Handle long-running tasks with progress tracking and checkpointing'],
['data-lakehouse-architecture','Data','Design lakehouse with Delta Lake Iceberg and unified processing'],
['data-real-time-streaming-pipeline','Data','Build streaming pipelines with Kafka Streams and Flink'],
['data-quality-monitoring','Data','Monitor data quality with Great Expectations and dbt tests'],
['data-reverse-etl','Data','Implement reverse ETL syncing warehouse data to SaaS tools'],
['data-change-data-capture-patterns','Data','Implement CDC with Debezium and PostgreSQL logical replication'],
['data-data-mesh-implementation','Data','Implement data mesh with domain ownership and data products'],
['data-dimensional-modeling','Data','Design dimensional models with star schemas and SCDs'],
['data-data-lineage-tracking','Data','Track data lineage with column-level lineage and impact analysis'],
['data-feature-engineering-advanced','Data','Advanced feature engineering with temporal features and embeddings'],
['data-data-catalog-implementation','Data','Implement data catalogs with DataHub and metadata management'],
['data-schema-evolution','Data','Handle schema evolution with backward forward compatibility'],
['data-data-versioning','Data','Version datasets with DVC lakeFS and experiment tracking'],
['data-stream-processing-exactly-once','Data','Implement exactly-once stream processing with Kafka transactions'],
['data-graph-analytics','Data','Build graph analytics with Neo4j and community detection'],
['data-real-time-dashboards','Data','Build real-time dashboards with materialized views and WebSockets'],
['mobile-offline-first-architecture','Mobile','Build offline-first mobile apps with sync and conflict resolution'],
['mobile-push-notification-architecture','Mobile','Design push notifications with FCM APNs and segmentation'],
['mobile-app-performance-profiling','Mobile','Profile mobile performance covering CPU memory and frame rates'],
['mobile-ci-cd-fastlane-advanced','Mobile','Advanced mobile CI CD with Fastlane match and screenshots'],
['mobile-deep-linking-advanced','Mobile','Implement deep linking universal links and app clips'],
['mobile-biometric-auth-patterns','Mobile','Implement biometric auth with Face ID Touch ID and secure enclave'],
['mobile-background-processing','Mobile','Handle background tasks with work managers and silent push'],
['mobile-app-size-optimization','Mobile','Optimize app binary size with tree shaking and compression'],
['mobile-gesture-recognition','Mobile','Implement custom gesture recognition with multi-touch handling'],
['mobile-camera-ar-integration','Mobile','Integrate camera AR with ARKit ARCore and image processing'],
['testing-contract-testing-pact','Testing','Consumer-driven contract testing with Pact and CI integration'],
['testing-chaos-engineering','Testing','Chaos engineering with Chaos Monkey and hypothesis-driven experiments'],
['testing-load-testing-artillery','Testing','Load test APIs with Artillery scenario scripting and CI'],
['testing-visual-regression-percy','Testing','Visual regression testing with Percy for responsive testing'],
['testing-api-fuzzing-advanced','Testing','API fuzz testing with property-based and mutation testing'],
['testing-performance-benchmarking','Testing','Benchmark performance with micro-benchmarks and statistical analysis'],
['testing-test-data-management','Testing','Manage test data with factories fixtures and data masking'],
['testing-mutation-testing','Testing','Validate test quality with mutation testing using Stryker'],
['testing-snapshot-testing-advanced','Testing','Advanced snapshot testing with serializer customization'],
['testing-accessibility-e2e','Testing','E2E accessibility testing with screen readers and ARIA validation'],
['sre-error-budget-management','SRE','Manage error budgets with SLO definition and burn rate alerts'],
['sre-capacity-planning','SRE','Plan capacity with demand forecasting and scaling strategies'],
['sre-postmortem-culture','SRE','Build blameless postmortem culture with organizational learning'],
['devops-gitops-advanced','DevOps','Advanced GitOps with ArgoCD multi-cluster and drift detection'],
['devops-platform-engineering','DevOps','Build developer platforms with Backstage and self-service infra'],
['devops-observability-stack','DevOps','Build observability with Prometheus Loki Tempo and correlation'],
['devops-incident-management','DevOps','Automate incidents with PagerDuty escalation and runbooks'],
['devops-deployment-strategies','DevOps','Advanced deployment with blue-green canary and feature flags'],
['devops-ephemeral-environments','DevOps','Create ephemeral preview environments per PR with auto cleanup'],
['devops-cost-attribution','DevOps','Implement cloud cost attribution with tagging and anomaly alerts'],
['web3-smart-contract-upgrades','Web3','Upgradeable contracts with proxy patterns UUPS and storage layouts'],
['web3-defi-yield-aggregator','Web3','Build yield aggregators with strategy contracts and auto-compounding'],
['web3-nft-marketplace-backend','Web3','NFT marketplace with metadata standards and lazy minting'],
['web3-cross-chain-messaging','Web3','Cross-chain messaging with LayerZero Wormhole and CCIP'],
['web3-dao-governance-contracts','Web3','DAO governance with Governor contracts and vote delegation'],
['web3-gas-optimization-advanced','Web3','Advanced Solidity gas optimization with storage packing'],
['web3-account-abstraction','Web3','ERC-4337 account abstraction with smart wallets and paymasters'],
['web3-decentralized-identity','Web3','Decentralized identity with DIDs and verifiable credentials'],
['web3-token-vesting-contracts','Web3','Token vesting with cliff periods linear vesting and revocation'],
['web3-oracle-integration-patterns','Web3','Blockchain oracles with Chainlink and custom oracle design'],
['architecture-clean-architecture','Architecture','Clean Architecture with dependency inversion and use cases'],
['architecture-hexagonal-ports-adapters','Architecture','Hexagonal Architecture with ports adapters and domain isolation'],
['architecture-strangler-fig-migration','Architecture','Migrate monoliths with Strangler Fig incremental extraction'],
['architecture-saga-pattern','Architecture','Distributed transactions with Sagas choreography vs orchestration'],
['architecture-outbox-pattern','Architecture','Transactional Outbox for reliable event publishing with CDC'],
['architecture-domain-events','Architecture','Domain event systems with event buses and eventual consistency'],
['architecture-cqrs-read-models','Architecture','CQRS read models with projections and materialized views'],
['architecture-anti-corruption-layer','Architecture','Anti-corruption layers between bounded contexts with adapters'],
['architecture-bulkhead-pattern','Architecture','Bulkhead pattern for fault isolation with thread pools'],
['architecture-sidecar-pattern','Architecture','Sidecar patterns for cross-cutting concerns like logging and auth'],
['observability-distributed-tracing','Observability','Distributed tracing with OpenTelemetry and sampling strategies'],
['observability-custom-metrics','Observability','Custom metrics with RED USE methods and cardinality management'],
['observability-log-aggregation','Observability','Log aggregation with structured logging and trace correlation'],
['observability-alerting-strategy','Observability','Effective alerting with fatigue prevention and symptom-based alerts'],
['observability-dashboards-design','Observability','Monitoring dashboards with layout principles and actionable views'],
['observability-error-tracking-advanced','Observability','Advanced error tracking with deduplication and impact analysis'],
['observability-synthetic-monitoring','Observability','Synthetic monitoring with canary checks and user journey simulation'],
['observability-cost-monitoring','Observability','Real-time cost monitoring with budget alerts and optimization'],
['performance-database-query-optimization','Performance','Optimize queries with EXPLAIN analysis and index strategies'],
['performance-nodejs-profiling','Performance','Profile Node.js with CPU profiling memory leaks and flame graphs'],
['performance-web-bundle-optimization','Performance','Optimize bundles with code splitting tree shaking and lazy loading'],
['performance-cdn-optimization','Performance','Optimize CDN with cache headers purge strategies and edge computing'],
['performance-api-response-optimization','Performance','Optimize API responses with pagination compression and caching'],
['performance-memory-leak-detection','Performance','Detect memory leaks with heap snapshots and allocation tracking'],
['performance-concurrent-request-handling','Performance','Handle concurrent requests with event loops and backpressure'],
['performance-image-optimization-pipeline','Performance','Image optimization with format selection quality tuning and CDN'],
['auth-passwordless-implementation','Auth','Passwordless auth with magic links WebAuthn and passkeys'],
['auth-multi-tenant-rbac','Auth','Multi-tenant RBAC with role hierarchies and tenant isolation'],
['auth-session-management','Auth','Secure session management with rotation and fixation prevention'],
['auth-social-login-integration','Auth','Social login with Google GitHub Apple and account linking'],
['auth-api-key-management','Auth','API key management with generation rotation and rate limiting'],
['auth-mfa-implementation','Auth','MFA with TOTP WebAuthn SMS and recovery codes'],
['auth-jwt-best-practices','Auth','JWT best practices with short expiry refresh tokens and rotation'],
['auth-sso-saml-implementation','Auth','SSO with SAML 2.0 for enterprise identity federation'],
['compliance-gdpr-implementation','Compliance','GDPR with consent management data subject rights and DPIAs'],
['compliance-hipaa-safeguards','Compliance','HIPAA safeguards with PHI encryption and audit logging'],
['compliance-soc2-preparation','Compliance','SOC 2 preparation with evidence collection and monitoring'],
['compliance-pci-dss-implementation','Compliance','PCI DSS with cardholder data protection and segmentation'],
['compliance-accessibility-wcag','Compliance','WCAG 2.1 AA with ARIA landmarks and keyboard navigation'],
['compliance-data-residency','Compliance','Data residency with geo-fencing and regional storage controls'],
['dx-monorepo-tooling','DX','Monorepo tooling with Turborepo Nx and remote caching'],
['dx-developer-onboarding','DX','Developer onboarding with environment setup and ramp-up guides'],
['dx-code-generation-templates','DX','Code generation with templates scaffolding and custom generators'],
['dx-linting-formatting-setup','DX','Linting formatting with ESLint Prettier and pre-commit hooks'],
['dx-local-development-environment','DX','Local dev with Docker Compose env vars and hot reloading'],
['dx-inner-loop-optimization','DX','Optimize inner loop with fast builds and incremental compilation'],
['dx-api-mocking-development','DX','API mocking with MSW Prism and contract-based mock generation'],
['dx-developer-analytics','DX','Developer productivity with DORA metrics and cycle time tracking'],
['game-ecs-architecture','Game','ECS architecture with data-oriented design and system scheduling'],
['game-procedural-world-generation','Game','Procedural worlds with noise functions biomes and terrain systems'],
['game-multiplayer-netcode','Game','Multiplayer netcode with prediction reconciliation and lag compensation'],
['game-shader-effects','Game','Shader effects with water fire fog bloom in GLSL HLSL'],
['game-dialogue-system','Game','Branching dialogue with dialogue trees conditions and localization'],
['game-inventory-system','Game','Inventory systems with stacking equipment slots and crafting'],
['game-save-system','Game','Save systems with serialization versioning and cloud sync'],
['game-particle-system','Game','Particle systems with emitters forces collisions and GPU instancing'],
['iot-sensor-data-pipeline','IoT','IoT sensor pipelines with MQTT time-series and real-time alerting'],
['iot-edge-ml-deployment','IoT','Edge ML with TensorFlow Lite ONNX and OTA updates'],
['iot-device-provisioning','IoT','Device provisioning with zero-touch enrollment and certificates'],
['iot-digital-twin-implementation','IoT','Digital twins with state sync simulation and predictive maintenance'],
['iot-fleet-management-ota','IoT','IoT fleet management with OTA updates and A/B deployments'],
['workflow-approval-system','Workflow','Approval workflows with multi-level delegation and audit trails'],
['workflow-document-processing','Workflow','Document processing with OCR classification and extraction'],
['workflow-email-automation-advanced','Workflow','Email automation with drip campaigns and behavioral triggers'],
['workflow-report-generation','Workflow','Report generation with data aggregation and PDF rendering'],
['workflow-task-orchestration','Workflow','Task orchestration with Temporal Step Functions and recovery'],
['networking-websocket-scaling','Networking','Scale WebSockets with sticky sessions and pub/sub backends'],
['networking-grpc-service-design','Networking','gRPC services with protobuf streaming and load balancing'],
['networking-api-gateway-patterns','Networking','API gateway with routing authentication and rate limiting'],
['networking-dns-architecture','Networking','DNS architecture with failover GeoDNS and service discovery'],
['networking-http3-quic','Networking','HTTP/3 QUIC with connection migration and zero-RTT'],
['writing-technical-blog-posts','Writing','Technical blog posts with structure code examples and SEO'],
['writing-api-documentation','Writing','API docs with OpenAPI specs examples and authentication guides'],
['writing-release-notes-generator','Writing','Release notes from git with conventional commits formatting'],
['writing-rfc-template','Writing','Technical RFCs with problem statement solution and alternatives'],
['writing-incident-report','Writing','Incident reports with timeline root cause and action items'],
['writing-architecture-decision-record','Writing','ADRs with context decision consequences and superseded records'],
['writing-runbook-template','Writing','Operational runbooks with procedures alerts and escalation'],
['writing-postmortem-template','Writing','Blameless postmortems with timeline factors and prevention'],
];

skills.forEach(([id,cat,desc]) => { const s = mk('skill',id,cat,desc); if(s) newS.push(s); });

// === 40+ AGENTS ===
const agents = [
['ai-pair-programmer','AI pair programmer writing code alongside you catching bugs in real-time'],
['architecture-reviewer','Reviews system architecture for scalability reliability and cost'],
['api-design-reviewer','Reviews API designs for consistency usability and standards'],
['dependency-auditor','Audits dependencies for vulnerabilities licenses and outdated packages'],
['migration-planner','Plans migrations with step-by-step plans and rollback strategies'],
['performance-profiler','Profiles performance identifying bottlenecks and memory leaks'],
['test-coverage-analyzer','Analyzes test coverage gaps suggesting critical tests to add'],
['error-pattern-detector','Detects recurring error patterns suggesting systematic fixes'],
['accessibility-auditor-agent','Audits web apps for WCAG accessibility compliance'],
['cost-optimizer-agent','Optimizes cloud costs analyzing usage and recommending rightsizing'],
['compliance-checker','Checks code and infra for GDPR HIPAA SOC 2 compliance violations'],
['documentation-generator','Generates documentation from code with API docs and diagrams'],
['refactoring-advisor','Advises on refactoring identifying code smells and patterns'],
['incident-responder-agent','Assists during incidents with diagnosis and mitigation'],
['release-manager','Manages releases with changelogs version bumps and rollback plans'],
['schema-designer','Designs database schemas optimizing for query patterns'],
['security-scanner-agent','Scans for vulnerabilities in dependencies configs and code'],
['devops-automator','Automates DevOps setting up CI CD monitoring and provisioning'],
['data-pipeline-builder','Builds data pipelines handling ETL streaming and batch processing'],
['ux-reviewer','Reviews UI UX for usability accessibility and responsiveness'],
['tech-debt-tracker','Tracks technical debt categorizing issues and prioritizing fixes'],
['onboarding-assistant','Helps new developers onboard explaining architecture and conventions'],
['code-quality-guardian','Guards code quality enforcing conventions and complexity limits'],
['integration-tester','Designs integration tests for API contracts and e2e flows'],
['feature-flag-manager','Manages feature flags with rollouts targeting and cleanup'],
['monitoring-setup-agent','Sets up monitoring with dashboards alerts and SLOs'],
['database-tuner','Tunes databases analyzing slow queries and suggesting indexes'],
['log-analyzer','Analyzes logs identifying patterns and correlating events'],
['chaos-engineer-agent','Plans chaos experiments testing resilience with controlled failures'],
['sprint-retrospective-facilitator','Facilitates retrospectives with feedback and improvement suggestions'],
['code-complexity-analyzer','Analyzes cyclomatic and cognitive complexity with dependency depth'],
['api-compatibility-checker','Checks API backward compatibility detecting breaking changes'],
['infrastructure-cost-advisor','Advises on cost optimization with reserved and spot strategies'],
['deployment-rollback-advisor','Advises on rollback strategies analyzing risk'],
['error-budget-tracker','Tracks SLO error budgets calculating burn rates'],
['dependency-update-advisor','Advises on updates analyzing changelogs and breaking changes'],
['performance-regression-detector','Detects performance regressions across commits'],
['data-model-reviewer','Reviews data models for normalization and query performance'],
['configuration-auditor','Audits configs for security best practices and consistency'],
['codebase-health-scorer','Scores codebase health across coverage complexity and freshness'],
];

agents.forEach(([id,desc]) => { const a = mk('agent',id,'',desc); if(a) newA.push(a); });

// === 50+ COMMANDS ===
const commands = [
['profile-performance','Profile application performance and identify bottlenecks'],
['scan-vulnerabilities','Scan codebase for security vulnerabilities in deps and code'],
['generate-api-docs','Generate OpenAPI documentation from code annotations'],
['analyze-bundle','Analyze JS bundle size and suggest code splitting'],
['check-accessibility','Run WCAG accessibility audit and report violations'],
['lint-docker','Lint Dockerfiles for best practices and security'],
['validate-schema','Validate database schema for normalization and indexing'],
['estimate-cost','Estimate cloud infrastructure costs for current architecture'],
['scaffold-microservice','Scaffold microservice with standard structure and CI CD'],
['setup-monitoring','Set up monitoring with metrics logging and alerting'],
['create-migration','Create database migration files with up down scripts'],
['audit-dependencies','Audit dependencies for vulnerabilities licenses and updates'],
['generate-tests','Generate tests for uncovered code paths'],
['optimize-queries','Optimize database queries with EXPLAIN and index suggestions'],
['setup-ci-cd','Set up CI CD pipeline with build test lint deploy'],
['create-env-template','Create environment variable template with validation'],
['scaffold-api-endpoint','Scaffold API endpoint with handler validation and tests'],
['run-security-scan','Run security scan with SAST dependency and config audit'],
['generate-types','Generate TypeScript types from schemas or JSON samples'],
['setup-feature-flags','Set up feature flag infrastructure with cleanup tools'],
['create-data-seed','Create database seed scripts with realistic test data'],
['validate-env','Validate environment config against schema'],
['setup-error-tracking','Set up Sentry Bugsnag with source maps and alerts'],
['scaffold-component','Scaffold component with props types tests and stories'],
['run-load-test','Run load tests and generate performance reports'],
['create-backup-strategy','Create backup strategy with scheduling and retention'],
['setup-rate-limiting','Set up API rate limiting with configurable limits'],
['generate-er-diagram','Generate ER diagrams from database schema'],
['scaffold-worker','Scaffold background worker with queue and monitoring'],
['check-code-quality','Run code quality checks for complexity and coverage'],
['generate-mock-data','Generate realistic mock data for testing'],
['setup-cors','Configure CORS policies for API endpoints'],
['validate-openapi','Validate OpenAPI spec for completeness and correctness'],
['scaffold-test-suite','Scaffold test suite with unit integration and e2e structure'],
['analyze-imports','Analyze imports find circular imports and optimize'],
['check-licenses','Check dependency licenses for compliance'],
['generate-dockerfile','Generate optimized Dockerfile with multi-stage builds'],
['setup-pre-commit','Configure pre-commit hooks with linting and formatting'],
['create-pr-template','Create PR template with checklist and review guidelines'],
['scaffold-auth','Scaffold auth system with login register and password reset'],
['generate-graphql-schema','Generate GraphQL schema from database models'],
['check-dead-code','Find dead code unused exports and unreachable functions'],
['setup-logging','Configure structured logging with levels and rotation'],
['validate-k8s-manifests','Validate K8s manifests for best practices and security'],
['scaffold-webhook','Scaffold webhook with signature verification and retry'],
['generate-sdk','Generate client SDK from API specification'],
['check-sql-injection','Scan for SQL injection vulnerabilities'],
['setup-caching','Configure caching with Redis or in-memory strategies'],
['scaffold-cli-tool','Scaffold CLI tool with argument parsing and completion'],
['generate-changelog-cmd','Generate changelog from conventional commits'],
];

commands.forEach(([id,desc]) => { const c = mk('command',id,'',desc); if(c) newC.push(c); });

D.skills.push(...newS);
D.agents.push(...newA);
D.commands.push(...newC);

console.log('Added:', newS.length, 'skills,', newA.length, 'agents,', newC.length, 'commands');
console.log('FINAL: Skills:', D.skills.length, 'Agents:', D.agents.length, 'Commands:', D.commands.length);
console.log('TOTAL:', D.skills.length + D.agents.length + D.commands.length);

// Write data file
const output = 'window._JARVIS_RAW = ' + JSON.stringify(D) + ';';
fs.writeFileSync('src/dashboard-data.js', output, 'utf8');

// Build base64 HTML
const b64 = Buffer.from(JSON.stringify(D)).toString('base64');
let html = fs.readFileSync('src/index.html', 'utf8');

const appMarker = 'let allItems = [];';
const appStart = html.lastIndexOf(appMarker);
const lastScript = html.lastIndexOf('<script>', appStart - 200);
const htmlBefore = html.substring(0, lastScript);
const appCode = html.substring(appStart);

const newHtml = htmlBefore + '<script>\nvar JARVIS_DATA = JSON.parse(atob("' + b64 + '"));\n' + appCode;
fs.writeFileSync('src/index.html', newHtml, 'utf8');

const opens = (newHtml.match(/<script/gi) || []).length;
const closes = (newHtml.match(/<\/script>/gi) || []).length;
console.log('HTML:', (newHtml.length/1024/1024).toFixed(1), 'MB | scripts:', opens, '/', closes);
